### ISSUE TITLE
Give names to magic numbers

### ISSUE THREAD

**Issue by maxvipon** [m-novikov/tzlookup#2]
What is `3241800` and `3600` in

``` js
var idx = arr[3241800 - 3600 * Math.floor(lat * 10 + 0.5) - Math.floor(lon * 10 + 0.5)];
```

?

And what means `10` and `0.5` in operation with the coordinate?

Let's give them names or annotations!

**Comment by m-novikov** [comment]
Using constants here heavily decreases performance.
(Added commentary on array index computation.)[https://github.com/m-novikov/tzlookup/blob/a1fd8797ba7208c28532a7f49873d3f4f4df9f8e/index.js#L30]
